### ISSUE TITLE
Allow for screen to dim (or go to 0% brightness) after a certain amount of time

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/pi-kiosk#2]
For this feature to be useful:

  1. A timeout could be configured, after which (if there's no activity), the screen could dim to a preconfigured level (e.g. 10%).
  2. Tapping anywhere on the display while the screen is dimmed would first 'wake' the display and bring it to full brightness, then after that's done, the user could touch elements on the display.

That latter point would require a bit more work—not sure if the Pi Touch Display 2 has integration into Linux itself to have some kind of automatic screen dimming support out of the box (or failing that, turn it off or dim it to 0%)...

**Comment by geerlingguy** [comment]
Note: There is built-in screen blanking functionality ([settings for it are in the Pi Configuration app, or in `raspi-config`](https://www.raspberrypi.com/documentation/computers/configuration.html#desktop)), but it doesn't seem to include much configurability... or the option of making the screen go dim instead of _off_.

**Comment by geerlingguy** [comment]
I did find the command `swayidle -w timeout 600 'wlopm --off \*' resume 'wlopm --on \*' &` tucked away inside `~/.config/labwc/autostart`. If the timeout is 10 minutes, that may be where it's set...

**Comment by geerlingguy** [comment]
From @6by9 on the Pi Forums:

> I suspect this is will be common across any touch device under labwc or Wayfire, and wants to be masked at that level.
The tricky part is likely to be that a single touch almost always ends up moving slightly, and is registering effectively "button down". So effectively you've had a first "movement" that is potentially ignored as we unblank, but unlike a mouse you've now got more "down" events triggering things. So you actually want to ignore events until the first "up" response has been received. Not my area of knowledge for how that is implemented.

So it sounds like a fix could be made, but it may be a little complicated. It'd be awesome to have that fix on the OS level so I don't have to do some weird shenanigans with a system service.

For now, I'm just touching in a part of the screen where I know there are no buttons.

**Comment by gabeklavans** [comment]
It's probably broken now that everything is wayland, but you can take a look at my fork of this pi-touchscreen-dimmer. I've been using it to get auto dimming on my pi for years now https://github.com/gabeklavans/pi-touchscreen-dimmer

**Comment by rohtua** [comment]
It's more of a workaround than fix but I've setup an automation in Home Assistant that will turn the display on/off when motion is detected. It doesn't fix the issue however does mean that when someone's in the room and may want to use the panel the display is on so they don't accidentally press a button when waking the screen up. 

I'm using a Pi 3B with Bookworm 64bit installed and the original Raspberry Pi display so there may be some difference. 

You can turn the backlight on or off by changing the value in `/sys/class/backlight/10-0045/bl_power`
Note: the 10-0045 may change with the version/type of screen along with the values of `bl_power`

For my display setting `bl_power` to `0 = on` and `4 = off`. Although from testing it appears that as long as the value is set to anything other than 0 it turns the display off but not 100% sure if its doing something else in the background with the value. I established my values by turning on screen blanking in `raspi-config` and checking the value when it turned the screen off. 

To setup the automation I setup passwordless SSH authentication between Home Assistant and the Pi.

On the Pi I then created two scripts and changed the permissions for `bl_power`:

`sudo chmod 777 /sys/class/backlight/10-0045/bl_power`

Backlight On
```
#!/bin/bash
echo 0 > /sys/class/backlight/10-0045/bl_power
```

Backlight Off
```
#!/bin/bash
echo 4 > /sys/class/backlight/10-0045/bl_power
```

I had to create them as scripts on the Pi as running the command directly through Home Assistant would fail whereas calling the script didn't. 

Then I setup shell commands in Home Assistant by adding the below to my `configuration.yaml`

```
shell_command:
    cp_backlight_off: ssh -i /config/.ssh/id_rsa -o 'StrictHostKeyChecking=no' {USER}@192.168.1.127 /home/{USER}/kiosk/backlight_off.sh
    cp_backlight_on: ssh -i /config/.ssh/id_rsa -o 'StrictHostKeyChecking=no' {USER}@192.168.1.127 /home/{USER}/kiosk/backlight_on.sh
```

You can run the command directly from the Home Assistant terminal with the `-o 'StrictHostKeyChecking=no'` option however when run as part of an automation it is required (at least I couldn't figure out how to get round it).

After a restart of HA to get the shell commands to appear I created two automations. 

```
alias: Control Panel Backlight On
description: Turn on the control panel backlight
triggers:
  - type: motion
    device_id: 5edc0dfac74a3d66ca014d9842f949bc
    entity_id: 6d291b8c0219488b10f4d1bca8271668
    domain: binary_sensor
    trigger: device
conditions: []
actions:
  - action: shell_command.cp_backlight_on
    metadata: {}
    data: {}
mode: single
```

```
alias: Control Panel Backlight Off
description: Turn off the control panel backlight
triggers:
  - type: no_motion
    device_id: 5edc0dfac74a3d66ca014d9842f949bc
    entity_id: 6d291b8c0219488b10f4d1bca8271668
    domain: binary_sensor
    trigger: device
conditions: []
actions:
  - action: shell_command.cp_backlight_off
    metadata: {}
    data: {}
mode: single
```

Now whenever motion is detected the screen comes on and goes off when people leave the room. Like I said it doesn't fix the issue but depending on use case it may do the job. A possible next step would be to present the backlight controls to HA as entities that could then be used as part of a normal motion-activated blueprint rather than create two seperate automations.
